### ISSUE TITLE
Please make it work with PM 3.11.x

### ISSUE THREAD

**Issue by Invy55** [MisteFr/ScoreboardsPE#25]

**Comment by MlsDmitry** [comment]
it's work! 
If you have the issue that lines not displaying but display name of the scoreboard displays, you can do -> $scoreboard->addEntry($entry, [$p]) without $p it would't displayed.
also you can go to ScoreboardAPI and add this line 
`if (empty($this->scoreboardViewers[$scoreboard->getObjectiveName()])) return $this->getServer()->getOnlinePlayers();`
 after this line 
`if (!isset($this->scoreboardViewers[$scoreboard->getObjectiveName()]))
            return [];`
It's api bug, I haven't pull request it yet. It's logical mistake, because then he(jason) didn't get any entry players he ask for getScoreboardViewers() before add something to this array.
