### ISSUE TITLE
Add API to remove all lines 

### ISSUE THREAD

**Issue by CaptainDuck** [MisteFr/ScoreboardsPE#9]
Because sometimes when you add a new line, it duplicates..
![image](https://user-images.githubusercontent.com/12457471/47252754-25cc9d80-d47c-11e8-9330-c90b80ee45b2.png)

``` php
$scoreboard->setLine($player, 5, $this->formatMessage("§3[§7Lvl§b{LVL}§7: §b{EXP}§7/§b{EXPNEEDED}§3]", $player));
//Updated by tasks..

**Comment by MisteFr** [comment]
Hey,
Thanks for your feedback !
Can you send me the code you are using on Twitter (@MisteFr) or discord (Miste#0001) because I never had this issue.
Concerning your API request, I will implement that asap (next week), for the moment you can use removeLine() or delete() the sc and create another one.

**Comment by SuperKali** [comment]
@CaptainDuck some bug
